
import "./globals.css";
import { ToastProvider } from "@/providers/ToastProvider";
import { UploadProvider } from "@/context/UploadContext";
import {Header}  from "@/components/layout/Header";
import  {Footer}  from "@/components/layout/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='flex flex-col pt-[100px]'>
        <Header />
        <ToastProvider />
        <UploadProvider >
        <main className =''>
        {children}
          </main>
     
          </UploadProvider>
          <Footer />
       </body>
    </html>
  );
}
